name: dyglib-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - anaconda::cmake
  - conda-forge::python-devtools
  - conda-forge::cudatoolkit
  - zip
  - numpy=1.26
  - pandas=2.2
  - tqdm
  - tabulate
  - pytorch::pytorch=2.1
  - pytorch::pytorch-cuda=11.8
  - pip:
      - wandb==0.23.1
